### PR TITLE
feat: add time picker

### LINKED ISSUE #9: Time setting field is not much user friendly
Currently looking like: 
Screenshot_2024-10-03-22-41-53-707_com android chrome

I like to contribute as: 
download

### PR DESCRIPTION
**Pull request by Prithwi32**
*Added time picker where in which user can set time either through draggable or dropdown selection, then time is set accordingly after clicking on done button

closes: #9

### CODE REVIEW

**Comment by Prithwi32** [comment]
@heysagnik please could you review changes and let me know feedback

**Comment by heysagnik** [comment]
The UI is good but few logics implemented previously by me isn't in this. Like when you schedule in the bottom bar and add a task it should be automatically added to the schedule task quadrant. And when any task (rendered component) is moved to schedule quadrant , it should ask for the time and then it would move

**Comment by Prithwi32** [comment]
> The UI is good but few logics implemented previously by me isn't in this. Like when you schedule in the bottom bar and add a task it should be automatically added to the schedule task quadrant. And when any task (rendered component) is moved to schedule quadrant , it should ask for the time and then it would move

I checked before sir, when we add task it automatically adds to do quadrant and then when we moved to schedule quadrant it asks time to set right

**Comment by heysagnik** [comment]
Check when writing in the Input bar if I select a time it should get added to the scheduled quadrant not the Do quadrant 
https://github.com/user-attachments/assets/663a59b4-9fe8-4e2b-82d7-1872557ec42c

**Comment by Prithwi32** [comment]
> Check when writing in the Input bar if I select a time it should get added to the scheduled quadrant not the Do quadrant https://github.com/user-attachments/assets/663a59b4-9fe8-4e2b-82d7-1872557ec42c

Okay i will change that

**Comment by Prithwi32** [comment]
@heysagnik hello, could you check changes now

**Comment by Prithwi32** [comment]
@heysagnik it's been 4 days.. could u review my PR please

**Comment by heysagnik** [comment]
> @heysagnik it's been 4 days.. could u review my PR please

So sorry.

**Comment by Prithwi32** [comment]
> > @heysagnik it's been 4 days.. could u review my PR please
> 
> So sorry.

No problem
.. Thank you 😊

**Pull request merged**
